#!python

import argparse
import os
import logging

import sheer.indexer


if __name__ == '__main__':

    parser = argparse.ArgumentParser(prog='sheer')

    subparsers = parser.add_subparsers()

    index_parser = subparsers.add_parser('index', help='load content into Elasticsearch')

    index_parser.add_argument('location')
    index_parser.add_argument('--elasticsearch_index', '-e', 
            default= os.environ.get('SHEER_ELASTICSEARCH_INDEX', 'http://localhost:9200/content/'))
                
    index_parser.set_defaults(func=sheer.indexer.index_args)

    for p in [parser, index_parser]:
        p.add_argument('--debug', help="print debugging output to the console", action='store_true')

    args = parser.parse_args()


    if args.debug:
        logger = logging.getLogger("")
        logger.setLevel(logging.DEBUG)

    args.func(args)

    
